### ISSUE TITLE
Please update PWM version in your Dockerhub

### ISSUE THREAD

**Issue by raphael5151** [fjudith/docker-pwm#5]
Hi,
I have some issues with the docker version wich is used in your docker container. Could you please update this container with a never version of pwm?
I use yopur container with a nginx as reverse proxy. Often, I get a blank page and the nginx doesen't redirect to the correct URL. It's a known issue from pwm. 

Thanks a lot
Raphael

**Comment by fjudith** [comment]
Hello,

I pushed 1.9.0, 1.9.1 and 2.0.0-SNAPSHOT tags. Could you tell me how it works on your side ?

**Comment by raphael5151** [comment]
Thanks a lot! 
Unfortunately the new release doesen't fix my problem. I think, the nginx configuration isn't at its best.

**Comment by BloodyIron** [comment]
Any chance we can get latest updated please? :) Also, unsure what 2.0.0 adds as I can't find release notes from the pwm devs, any ideas?

**Comment by BloodyIron** [comment]
@fjudith completed? When will updated docker images be uploaded to dockerhub? :)

**Comment by fjudith** [comment]
OCIs were pushed to both DockerHub and Github Container Repository

**Comment by BloodyIron** [comment]
@fjudith yay! Thanks a tonne for this and all your other work! \o/ Much appreciated :)
