### ISSUE TITLE
Error 5015

### ISSUE THREAD

**Issue by gigiwest123** [fjudith/docker-pwm#6]
Hi,

When I try to import by using keystore in the container it doesn't recognise the command, and when I select the option to pull the self signed certificate from from the server I get the following error when I try to login:

An error has occurred. If this error occurs repeatedly please contact your help desk.

5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL (ldap error during searchID=1, context=DC=domainname,DC=com, error=javax.naming.PartialResultException, cause:javax.naming.CommunicationException: domainname.com:636, cause:javax.net.ssl.SSLException: Couldn't kickstart handshaking, cause:java.net.SocketException: Connection reset by peer (Write failed)))

**Comment by fjudith** [comment]
Have you tried to convert your Keystore to PKCS12 ?

The image is running pretty recent version of Java. JRE-11

**Comment by gigiwest123** [comment]
Do I need to do this on the host or within the container?
