### ISSUE TITLE
unable to obtain file lock on file /usr/share/pwm/applicationPath.lock

### ISSUE THREAD

**Issue by salaun-urennes1** [fjudith/docker-pwm#7]
Hello,

I'm facing a problem while running a Docker container based on https://hub.docker.com/r/fjudith/pwm

Here is how I start the container: `docker run --detach --rm -it --name=pwm -p 8080:8080 -v /data/webapps/pwm-docker/:/usr/share/pwm fjudith/pwm`

The shared volume `/usr/share/pwm` let the host and container share the PWM configuration files.

But PWM complains at startup:
```
2021-03-10T07:54:02.701947Z, DEBUG, http.ContextManager, {#,context} configuration file was loaded from /usr/share/pwm/PwmConfiguration.xml
log4j:WARN No appenders could be found for logger (password.pwm.util.logging.PwmLogManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2021-03-10T07:54:02Z, ERROR, pwm.FileLocker, unable to obtain file lock on file /usr/share/pwm/applicationPath.lock due to error: null
...
2021-03-10T07:56:02Z, FATAL, pwm.PwmApplication, 5082 ERROR_STARTUP_ERROR (unable to obtain application path file lock)
```

I had a look at the code and it seems that `applicationPath.lock` can't be relocated; it is under `PWM_APPLICATIONPATH` directory:

From `server/src/main/java/password/pwm/PwmEnvironment.java`
```
        FileLocker( )
        {
            final String lockfileName = config.readAppProperty( AppProperty.APPLICATION_FILELOCK_FILENAME );
            lockfile = new File( getApplicationPath(), lockfileName );
        }
```

Any way to make PWM create lock files outside my shared volume?
How do you suggest managing configuration files between host and container?

Thanks

**Comment by fbuchmeier-abi** [comment]
Hi @salaun-urennes1,

I've fixed this by removing the `sed` commands that are in place to redirect requests from `/` to `/pwm/`. Instead, I've updated the image to unpack `pwm` inside the `ROOT` folder.

This  works just fine in the latest tomcat:9.0.45 Docker image, I suspect PWM was launched twice which caused the File Locking issues.

Here is my diff:
```
diff --git a/debian/Dockerfile b/debian/Dockerfile
 
-FROM docker.io/amd64/tomcat:9-jre11-slim
+FROM docker.io/library/tomcat:9.0.45-jdk11-openjdk-buster
 
 LABEL maintainer="Florian JUDITH <florian.judith.b@gmail.com>"
 
@@ -17,65 +61,55 @@ ENV MYSQL_DRIVER_VERSION=8.0.15 \
     POSTGRES_DRIVER_VERSION=42.2.5 \
     MONGODB_DRIVER_VERSION=3.9.1 \
     MARIADB_DRIVER_VERSION=2.4.0 \
-    PWM_HOME=${CATALINA_HOME}/webapps/pwm \
+    PWM_HOME=${CATALINA_HOME}/webapps/ROOT \

-# Update server.xml to set pwm webapp to root
-RUN cd $CATALINA_HOME && \
-    xmlstarlet ed \
-    -P -S -L \
-    -i '/Server/Service/Engine/Host/Valve' -t 'elem' -n 'Context' \
-    -i '/Server/Service/Engine/Host/Context' -t 'attr' -n 'path' -v '/' \
-    -i '/Server/Service/Engine/Host/Context[@path="/"]' -t 'attr' -n 'docBase' -v 'pwm' \
-    -s '/Server/Service/Engine/Host/Context[@path="/"]' -t 'elem' -n 'WatchedResource' -v 'WEB-INF/web.xml' \
-    -i '/Server/Service/Engine/Host/Valve' -t 'elem' -n 'Context' \
-    -i '/Server/Service/Engine/Host/Context[not(@path="/")]' -t 'attr' -n 'path' -v '/ROOT' \
-    -s '/Server/Service/Engine/Host/Context[@path="/ROOT"]' -t 'attr' -n 'docBase' -v 'ROOT' \
-    -s '/Server/Service/Engine/Host/Context[@path="/ROOT"]' -t 'elem' -n 'WatchedResource' -v 'WEB-INF/web.xml' \
-    conf/server.xml
```

Regards,
Florian (just a random user).

**Comment by anwoke8204** [comment]
hello I am getting the following error with the latest docker pull.  how do I resolve this issue?

2022-02-01T02:54:51Z, ERROR, pwm.FileLocker, unable to obtain file lock on file /usr/share/pwm/applicationPath.lock due to error: null
2022-02-01T02:54:51Z, DEBUG, pwm.FileLocker, can't establish application file lock after 1m:6s, will retry;

**Comment by BloodyIron** [comment]
I'm getting:

ERROR, pwm.FileLocker, unable to obtain file lock on file /usr/share/pwm/applicationPath.lock due to error: null

With the latest image. What's up with this?

**Comment by BloodyIron** [comment]
The "solution" I've found was to add the environment variable PWM_APPLICATIONFLAGS, with value "NoFileLock". Supposedly this may be problematic, but I doubt it, since this is in an ephemeral docker container. I don't see a reason to worry about lock files not existing.

**Comment by fjudith** [comment]
I faced the issue on 2.0.5 until i realized that it disapear after sometimes the container started
![image](https://user-images.githubusercontent.com/17888379/230750491-a0e8d13d-5af6-417b-915d-75ff25deeb57.png)

**Comment by BloodyIron** [comment]
@fjudith has your image been updated past 2.0.0-SNAPSHOT? I thought that was the latest image version on your dockerhub?

**Comment by joasara** [comment]
Hi, I am having this same error. How can I solve that?

**Comment by BloodyIron** [comment]
I don't remember the details of "my solution" in my case. However here's some info that might be helpful to you @joasara 

1. I'm rocking: "image: fjudith/pwm:2.0.5-debian"
2. The PV/PVCs are SMB-backed with "driver: smb.csi.k8s.io"

So I don't think that NFS is necessarily a requirement for this, but hope this helps! :)
